import type {
  BankAccount,
  CreditCard,
  FamilyMember,
  Goal,
  Transaction,
} from '../types/finance'

export const MOCK_FAMILY_MEMBERS: FamilyMember[] = [
  {
    id: 'mem-lucas',
    name: 'Lucas Marte',
    role: 'Titular',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lucas',
    email: 'lucasmarte@gmail.com',
    monthlyIncome: 8500,
  },
  {
    id: 'mem-maria',
    name: 'Maria Marte',
    role: 'Cônjuge',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=maria',
    email: 'maria.marte@gmail.com',
    monthlyIncome: 6200,
  },
  {
    id: 'mem-pedro',
    name: 'Pedro Marte',
    role: 'Filho',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=pedro',
    monthlyIncome: 0,
  },
]

export const MOCK_BANK_ACCOUNTS: BankAccount[] = [
  {
    id: 'acc-nubank',
    name: 'Nubank Conta',
    holderId: 'mem-lucas',
    balance: 4200,
    type: 'checking',
  },
  {
    id: 'acc-inter',
    name: 'Inter Conta',
    holderId: 'mem-lucas',
    balance: 3100,
    type: 'checking',
  },
  {
    id: 'acc-itau',
    name: 'Itaú Poupança',
    holderId: 'mem-maria',
    balance: 8900,
    type: 'savings',
  },
]

export const MOCK_CREDIT_CARDS: CreditCard[] = [
  {
    id: 'card-nubank',
    name: 'Nubank Mastercard',
    holderId: 'mem-lucas',
    limit: 8000,
    currentBill: 2150.5,
    closingDay: 8,
    dueDay: 15,
    lastDigits: '5897',
    theme: 'black',
  },
  {
    id: 'card-inter',
    name: 'Inter Visa',
    holderId: 'mem-lucas',
    limit: 12000,
    currentBill: 4320,
    closingDay: 5,
    dueDay: 12,
    lastDigits: '4421',
    theme: 'lime',
  },
  {
    id: 'card-picpay',
    name: 'PicPay Mastercard',
    holderId: 'mem-maria',
    limit: 5000,
    currentBill: 980,
    closingDay: 20,
    dueDay: 27,
    lastDigits: '9033',
    theme: 'white',
  },
]

export const MOCK_GOALS: Goal[] = [
  {
    id: 'goal-viagem',
    name: 'Viagem Nordeste',
    category: 'Viagem',
    targetAmount: 12000,
    currentAmount: 4800,
    dueDate: '2026-08-01',
    memberId: 'mem-lucas',
  },
  {
    id: 'goal-reserva',
    name: 'Reserva de emergência',
    category: 'Poupança',
    targetAmount: 20000,
    currentAmount: 13200,
    dueDate: '2026-12-31',
    memberId: null,
  },
  {
    id: 'goal-note',
    name: 'Notebook novo',
    category: 'Tecnologia',
    targetAmount: 5500,
    currentAmount: 900,
    dueDate: '2026-06-15',
    memberId: 'mem-pedro',
  },
  {
    id: 'goal-carro',
    name: 'Manutenção do carro',
    category: 'Transporte',
    targetAmount: 4000,
    currentAmount: 2600,
    dueDate: '2026-05-01',
    memberId: 'mem-lucas',
  },
]

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-001',
    type: 'income',
    description: 'Salário Lucas',
    category: 'Salário',
    value: 8500,
    date: '2026-04-05',
    memberId: 'mem-lucas',
    accountId: 'acc-nubank',
    installments: 1,
    isRecurring: false,
    isPaid: true,
    status: 'completed',
  },
  {
    id: 'tx-002',
    type: 'income',
    description: 'Salário Maria',
    category: 'Salário',
    value: 6200,
    date: '2026-04-03',
    memberId: 'mem-maria',
    accountId: 'acc-itau',
    installments: 1,
    isRecurring: false,
    isPaid: true,
    status: 'completed',
  },
  {
    id: 'tx-003',
    type: 'expense',
    description: 'Supermercado Semanal',
    category: 'Alimentação',
    value: 420.9,
    date: '2026-04-12',
    memberId: 'mem-maria',
    accountId: 'card-nubank',
    installments: 1,
    isRecurring: false,
    isPaid: true,
    status: 'completed',
  },
  {
    id: 'tx-004',
    type: 'expense',
    description: 'Conta de Luz',
    category: 'Moradia',
    value: 154,
    date: '2026-04-10',
    dueDate: '2026-04-21',
    memberId: 'mem-lucas',
    accountId: 'acc-nubank',
    installments: 1,
    isRecurring: true,
    isPaid: false,
    status: 'pending',
  },
  {
    id: 'tx-005',
    type: 'expense',
    description: 'Conta de água',
    category: 'Manutenção',
    value: 100,
    date: '2026-04-08',
    memberId: 'mem-lucas',
    accountId: 'acc-inter',
    installments: 1,
    isRecurring: false,
    isPaid: true,
    status: 'completed',
  },
  {
    id: 'tx-006',
    type: 'expense',
    description: 'Passeio no parque',
    category: 'Lazer',
    value: 80,
    date: '2026-04-07',
    memberId: 'mem-pedro',
    accountId: 'card-inter',
    installments: 1,
    isRecurring: false,
    isPaid: true,
    status: 'completed',
  },
  {
    id: 'tx-007',
    type: 'expense',
    description: 'Farmácia',
    category: 'Saúde',
    value: 210.5,
    date: '2026-04-06',
    memberId: 'mem-maria',
    accountId: 'card-picpay',
    installments: 1,
    isRecurring: false,
    isPaid: true,
    status: 'completed',
  },
  {
    id: 'tx-008',
    type: 'expense',
    description: 'Combustível',
    category: 'Transporte',
    value: 320,
    date: '2026-04-04',
    memberId: 'mem-lucas',
    accountId: 'card-inter',
    installments: 1,
    isRecurring: false,
    isPaid: true,
    status: 'completed',
  },
  {
    id: 'tx-009',
    type: 'income',
    description: 'Freelance design',
    category: 'Extra',
    value: 1800,
    date: '2026-03-28',
    memberId: 'mem-lucas',
    accountId: 'acc-nubank',
    installments: 1,
    isRecurring: false,
    isPaid: true,
    status: 'completed',
  },
  {
    id: 'tx-010',
    type: 'expense',
    description: 'Restaurante',
    category: 'Alimentação',
    value: 189.9,
    date: '2026-03-25',
    memberId: 'mem-lucas',
    accountId: 'card-nubank',
    installments: 1,
    isRecurring: false,
    isPaid: true,
    status: 'completed',
  },
  {
    id: 'tx-011',
    type: 'expense',
    description: 'Academia',
    category: 'Saúde',
    value: 120,
    date: '2026-03-22',
    memberId: 'mem-lucas',
    accountId: 'acc-inter',
    installments: 1,
    isRecurring: true,
    isPaid: true,
    status: 'completed',
  },
  {
    id: 'tx-012',
    type: 'expense',
    description: 'Netflix',
    category: 'Assinaturas',
    value: 55.9,
    date: '2026-03-18',
    memberId: null,
    accountId: 'card-picpay',
    installments: 1,
    isRecurring: true,
    isPaid: true,
    status: 'completed',
  },
  {
    id: 'tx-013',
    type: 'expense',
    description: 'Compra parcelada — Sofá',
    category: 'Moradia',
    value: 450,
    date: '2026-03-10',
    memberId: 'mem-maria',
    accountId: 'card-inter',
    installments: 6,
    currentInstallment: 2,
    isRecurring: false,
    isPaid: true,
    status: 'completed',
  },
  {
    id: 'tx-014',
    type: 'income',
    description: 'Reembolso saúde',
    category: 'Saúde',
    value: 240,
    date: '2026-03-05',
    memberId: 'mem-maria',
    accountId: 'acc-itau',
    installments: 1,
    isRecurring: false,
    isPaid: true,
    status: 'completed',
  },
  {
    id: 'tx-015',
    type: 'expense',
    description: 'Uber',
    category: 'Transporte',
    value: 62.4,
    date: '2026-02-27',
    memberId: 'mem-pedro',
    accountId: 'card-nubank',
    installments: 1,
    isRecurring: false,
    isPaid: true,
    status: 'completed',
  },
  {
    id: 'tx-016',
    type: 'expense',
    description: 'Material escolar',
    category: 'Educação',
    value: 310,
    date: '2026-02-20',
    memberId: 'mem-pedro',
    accountId: 'acc-inter',
    installments: 1,
    isRecurring: false,
    isPaid: true,
    status: 'completed',
  },
  {
    id: 'tx-017',
    type: 'income',
    description: '13º salário',
    category: 'Salário',
    value: 4200,
    date: '2026-02-15',
    memberId: 'mem-maria',
    accountId: 'acc-itau',
    installments: 1,
    isRecurring: false,
    isPaid: true,
    status: 'completed',
  },
  {
    id: 'tx-018',
    type: 'expense',
    description: 'Manutenção predial',
    category: 'Manutenção',
    value: 580,
    date: '2026-02-10',
    memberId: 'mem-lucas',
    accountId: 'acc-nubank',
    installments: 1,
    isRecurring: false,
    isPaid: true,
    status: 'completed',
  },
  {
    id: 'tx-019',
    type: 'expense',
    description: 'Presente aniversário',
    category: 'Lazer',
    value: 150,
    date: '2026-02-08',
    memberId: 'mem-maria',
    accountId: 'card-picpay',
    installments: 1,
    isRecurring: false,
    isPaid: true,
    status: 'completed',
  },
  {
    id: 'tx-020',
    type: 'expense',
    description: 'Plano de saúde',
    category: 'Saúde',
    value: 890,
    date: '2026-02-05',
    memberId: 'mem-lucas',
    accountId: 'acc-inter',
    installments: 1,
    isRecurring: true,
    isPaid: true,
    status: 'completed',
  },
  {
    id: 'tx-021',
    type: 'income',
    description: 'Rendimento poupança',
    category: 'Investimentos',
    value: 42.8,
    date: '2026-01-31',
    memberId: null,
    accountId: 'acc-itau',
    installments: 1,
    isRecurring: false,
    isPaid: true,
    status: 'completed',
  },
  {
    id: 'tx-022',
    type: 'expense',
    description: 'IPTU (1ª parcela)',
    category: 'Moradia',
    value: 1200,
    date: '2026-01-20',
    memberId: 'mem-lucas',
    accountId: 'acc-nubank',
    installments: 10,
    currentInstallment: 1,
    isRecurring: false,
    isPaid: true,
    status: 'completed',
  },
  {
    id: 'tx-023',
    type: 'expense',
    description: 'Mercado',
    category: 'Alimentação',
    value: 512.3,
    date: '2026-01-14',
    memberId: 'mem-maria',
    accountId: 'card-nubank',
    installments: 1,
    isRecurring: false,
    isPaid: true,
    status: 'completed',
  },
  {
    id: 'tx-024',
    type: 'expense',
    description: 'Farmácia',
    category: 'Saúde',
    value: 88.7,
    date: '2026-01-08',
    memberId: 'mem-pedro',
    accountId: 'card-inter',
    installments: 1,
    isRecurring: false,
    isPaid: true,
    status: 'completed',
  },
]
